=== javanator/copycat/bukkitmodders-copycat/src/main/resources/pluginSettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/pluginSettings"
	xmlns:cc="http://www.example.org/pluginSettings" elementFormDefault="unqualified">

	<element name="configFile" type="cc:pluginConfig" />

	<complexType name="globalSettingsType">
		<sequence>
			<element name="prohibitedWorlds" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="world" type="string" minOccurs="0"
							maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="maxImageWidth" type="int" minOccurs="1"
				maxOccurs="1" />
			<element name="maxImageHeight" type="int" minOccurs="1"
				maxOccurs="1" />
			<element name="blockProfiles">
				<complexType>
					<sequence>
						<element name="blockProfile" type="cc:blockProfileType"
							minOccurs="1" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="playerSettingsType">
		<sequence>
			<element name="blockProfile" type="string" minOccurs="1"
				maxOccurs="1" />
			<element name="buildWidth" type="int" minOccurs="1"
				maxOccurs="1" default="64" />
			<element name="buildHeight" type="int" minOccurs="1"
				maxOccurs="1" default="64" />
			<element name="activeShortcut" type="string" />
			<element name="shortcuts" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="shortcut" minOccurs="0" maxOccurs="unbounded">
							<complexType>
								<attribute name="name" type="string" use="required" />
								<attribute name="url" type="string" use="required" />
							</complexType>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="playerName" type="string" use="required" />
		<attribute name="playerEnabled" type="boolean" use="required" />
	</complexType>

	<complexType name="blockProfileType">
		<sequence>
			<element name="block" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<attribute name="name" use="optional" type="string" />
					<attribute name="textureIndex" type="int" use="required" />
				</complexType>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>

	<complexType name="pluginConfig">
		<sequence>
			<element name="globalSettings" type="cc:globalSettingsType"
				minOccurs="1" maxOccurs="1" />

			<element name="preferences">
				<complexType>
					<sequence>
						<element name="playerPreferences" type="cc:playerSettingsType"
							minOccurs="0" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>

=== javanator/copycat/bukkitmodders-copycat/src/main/resources/defaultSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<cc:configFile xmlns:cc="http://www.example.org/pluginSettings" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/pluginSettings pluginSettings.xsd ">
	<globalSettings>
		<prohibitedWorlds>
			<world>prohibitedWorld</world>
			<world>anotherProhibitedWorld</world>
		</prohibitedWorlds>
		<!-- Increase with caution. -->
		<maxImageWidth>400</maxImageWidth>
		<maxImageHeight>100</maxImageHeight>

		<blockProfiles>
			<blockProfile name="wool">
				<block textureIndex="64" name="WOOL_WHITE" />
				<block textureIndex="113" name="WOOL_BLACK" />
				<block textureIndex="114" name="WOOL_GRAY" />
				<block textureIndex="129" name="WOOL_RED" />
				<block textureIndex="130" name="WOOL_PINK" />
				<block textureIndex="145" name="WOOL_GREEN" />
				<block textureIndex="146" name="WOOL_LIGHT_GREEN" />
				<block textureIndex="161" name="WOOL_BROWN" />
				<block textureIndex="162" name="WOOL_YELLOW" />
				<block textureIndex="177" name="WOOL_BLUE" />
				<block textureIndex="178" name="WOOL_LIGHT_BLUE" />
				<block textureIndex="193" name="WOOL_PURPLE" />
				<block textureIndex="194" name="WOOL_LIGHT_PURPLE" />
				<block textureIndex="209" name="WOOL_CYAN" />
				<block textureIndex="210" name="WOOL_ORANGE" />
				<block textureIndex="225" name="WOOL_LIGHT_GRAY" />
			</blockProfile>
			<blockProfile name="earth">
				<block textureIndex="103" name="NETHERACK" />
				<block textureIndex="2" name="DIRT" />
				<block textureIndex="1" name="STONE" />
				<block textureIndex="192" name="SANDSTONE" />
				<block textureIndex="7" name="BRICK" />
				<block textureIndex="66" name="SNOW_BLOCK" />
				<block textureIndex="72" name="CLAY" />
				<block textureIndex="4" name="WOOD_PLANK" />
				<block textureIndex="22" name="IRON_BLOCK" />
				<block textureIndex="23" name="GOLD_BLOCK" />
				<block textureIndex="24" name="DIAMOND_BLOCK" />
				<block textureIndex="105" name="GLOWSTONE" />
				<block textureIndex="144" name="LAPIS_LAZULI_BLOCK" />
				<block textureIndex="160" name="LAPIS_LAZULI_ORE" />
				<block textureIndex="37" name="OBSIDIAN" />
				<block textureIndex="74" name="NOTE_BLOCK" />
				<block textureIndex="36" name="MOSSY_COBBLESTONE" />
				<block textureIndex="33" name="IRON_ORE" />
				<block textureIndex="34" name="COAL_ORE" />
				<block textureIndex="50" name="DIAMOND_ORE" />
				<block textureIndex="32" name="GOLD_ORE" />
				<block textureIndex="51" name="REDSTONE_ORE" />
				<block textureIndex="16" name="COBBLESTONE" />
				<block textureIndex="175" name="ENDER_STONE" />
				<block textureIndex="48" name="SPONGE" />
				<block textureIndex="224" name="NETHER_BRICK" />
			</blockProfile>
			<blockProfile name="default">
				<block textureIndex="103" name="NETHERACK" />
				<block textureIndex="2" name="DIRT" />
				<block textureIndex="1" name="STONE" />
				<block textureIndex="192" name="SANDSTONE" />
				<block textureIndex="7" name="BRICK" />
				<block textureIndex="66" name="SNOW_BLOCK" />
				<block textureIndex="72" name="CLAY" />
				<block textureIndex="4" name="WOOD_PLANK" />
				<block textureIndex="22" name="IRON_BLOCK" />
				<block textureIndex="23" name="GOLD_BLOCK" />
				<block textureIndex="24" name="DIAMOND_BLOCK" />
				<block textureIndex="105" name="GLOWSTONE" />
				<block textureIndex="144" name="LAPIS_LAZULI_BLOCK" />
				<block textureIndex="160" name="LAPIS_LAZULI_ORE" />
				<block textureIndex="37" name="OBSIDIAN" />
				<block textureIndex="74" name="NOTE_BLOCK" />
				<block textureIndex="36" name="MOSSY_COBBLESTONE" />
				<block textureIndex="33" name="IRON_ORE" />
				<block textureIndex="34" name="COAL_ORE" />
				<block textureIndex="50" name="DIAMOND_ORE" />
				<block textureIndex="32" name="GOLD_ORE" />
				<block textureIndex="51" name="REDSTONE_ORE" />
				<block textureIndex="16" name="COBBLESTONE" />
				<block textureIndex="64" name="WOOL_WHITE" />
				<block textureIndex="113" name="WOOL_BLACK" />
				<block textureIndex="114" name="WOOL_GRAY" />
				<block textureIndex="129" name="WOOL_RED" />
				<block textureIndex="130" name="WOOL_PINK" />
				<block textureIndex="145" name="WOOL_GREEN" />
				<block textureIndex="146" name="WOOL_LIGHT_GREEN" />
				<block textureIndex="161" name="WOOL_BROWN" />
				<block textureIndex="162" name="WOOL_YELLOW" />
				<block textureIndex="177" name="WOOL_BLUE" />
				<block textureIndex="178" name="WOOL_LIGHT_BLUE" />
				<block textureIndex="193" name="WOOL_PURPLE" />
				<block textureIndex="194" name="WOOL_LIGHT_PURPLE" />
				<block textureIndex="209" name="WOOL_CYAN" />
				<block textureIndex="210" name="WOOL_ORANGE" />
				<block textureIndex="225" name="WOOL_LIGHT_GRAY" />
				<block textureIndex="175" name="ENDER_STONE" />
				<block textureIndex="48" name="SPONGE" />
				<block textureIndex="224" name="NETHER_BRICK" />
			</blockProfile>
		</blockProfiles>


	</globalSettings>

	<preferences>
		<playerPreferences playerEnabled="false" playerName="examplePlayer">

			<blockProfile>default</blockProfile>
			<buildWidth>64</buildWidth>
			<buildHeight>64</buildHeight>

			<shortcuts>
				<shortcut name="shortuctname" url="http://aurl" />
				<shortcut name="anothershortuctname" url="file://aurl" />
			</shortcuts>
		</playerPreferences>
	</preferences>
</cc:configFile>
